import sqlalchemy as sa
"""
Shared SQLAlchemy column mixins.

All domain models inherit from Base (database.py) and optionally from
these mixins to get UUID primary keys and standard timestamp columns.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


class UUIDPrimaryKeyMixin:
    """UUID v4 primary key, generated by Python (not the DB)."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at columns, always in UTC."""

    created_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        default=_now_utc,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        default=_now_utc,
        server_default=func.now(),
        onupdate=_now_utc,
    )
